function character(request, response) {
  response.status(200).json({
    characters: [
      // Main Piston Cup racers
      {
        name: "Lightning McQueen",
        number: 95,
        color: "red",
        type: "race car",
        model: "Chevrolet Corvette-inspired",
        league: "Piston Cup",
        hometown: "Radiator Springs",
        sponsor: "Rust-eze",
      },
      {
        name: "Chick Hicks",
        number: 86,
        color: "green",
        type: "race car",
        model: "Buick Regal 1987",
        league: "Piston Cup",
        hometown: "Unknown",
        sponsor: "Various",
      },
      {
        name: "Strip The King Weathers",
        number: 43,
        color: "blue",
        type: "race car",
        model: "Dinoco Plymouth Superbird",
        league: "Piston Cup",
        hometown: "Unknown",
        sponsor: "Dinoco",
      },

      // Radiator Springs residents
      {
        name: "Mater",
        type: "tow truck",
        color: "rusty brown",
        model: "International Harvester L-170",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Sally Carrera",
        type: "sports car",
        color: "blue",
        model: "Porsche 911 Carrera",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Doc Hudson",
        number: 51,
        type: "classic race car",
        color: "blue",
        model: "Hudson Hornet 1951",
        league: "Piston Cup (former)",
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Ramone",
        type: "lowrider",
        color: "varies (different paint jobs)",
        model: "Chevrolet Impala 1959",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Flo",
        type: "classic car",
        color: "aqua green",
        model: "Motorama Show Car",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Luigi",
        type: "compact car",
        color: "yellow",
        model: "Fiat 500",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Guido",
        type: "forklift",
        color: "blue",
        model: "Ferrari pit stop style",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Sheriff",
        type: "police car",
        color: "black and white",
        model: "Cop Car",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Fillmore",
        type: "hippie van",
        color: "orange and green",
        model: "VW Bus",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Sarge",
        type: "military jeep",
        color: "army green",
        model: "Jeep Willys",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Mack",
        type: "truck",
        color: "red",
        model: "Mack Super-Liner",
        league: null,
        hometown: "Unknown",
        sponsor: "Rust-eze",
      },
    ],
  });
}

export default character;
