function character(request, response) {
  response.status(200).json({
    characters: [
      // Personagens principais da Copa Pistão
      {
        name: "Lightning McQueen",
        number: 95,
        color: "vermelho",
        type: "carro de corrida",
        model: "Chevrolet Corvette inspirado",
        league: "Copa Pistão",
        hometown: "Radiator Springs",
        sponsor: "Rust-eze",
      },
      {
        name: "Chick Hicks",
        number: 86,
        color: "verde",
        type: "carro de corrida",
        model: "Buick Regal 1987",
        league: "Copa Pistão",
        hometown: "Não especificado",
        sponsor: "Vários",
      },
      {
        name: "Strip The King Weathers",
        number: 43,
        color: "azul",
        type: "carro de corrida",
        model: "Dinoco Plymouth Superbird",
        league: "Copa Pistão",
        hometown: "Não especificado",
        sponsor: "Dinoco",
      },

      // Galera de Radiator Springs
      {
        name: "Mate (Mater)",
        type: "caminhão guincho",
        color: "marrom enferrujado",
        model: "International Harvester L-170",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Sally Carrera",
        type: "carro esportivo",
        color: "azul",
        model: "Porsche 911 Carrera",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Doc Hudson",
        number: 51,
        type: "carro clássico de corrida",
        color: "azul",
        model: "Hudson Hornet 1951",
        league: "Copa Pistão (antiga)",
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Ramone",
        type: "lowrider",
        color: "varia (pinturas diferentes)",
        model: "Chevrolet Impala 1959",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Flo",
        type: "carro clássico",
        color: "verde água",
        model: "Motorama Show Car",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Luigi",
        type: "carro compacto",
        color: "amarelo",
        model: "Fiat 500",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Guido",
        type: "empilhadeira",
        color: "azul",
        model: "Ferrari pit stop style",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Sheriff",
        type: "carro de polícia",
        color: "preto e branco",
        model: "Cop Car",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Fillmore",
        type: "van hippie",
        color: "laranja e verde",
        model: "VW Bus",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Sarge",
        type: "jeep militar",
        color: "verde militar",
        model: "Jeep Willys",
        league: null,
        hometown: "Radiator Springs",
        sponsor: null,
      },
      {
        name: "Mack",
        type: "caminhão",
        color: "vermelho",
        model: "Mack Super-Liner",
        league: null,
        hometown: "Não especificado",
        sponsor: "Rust-eze",
      },
    ],
  });
}

export default character;
